// BF++ Code Generator — AST → C source.

use crate::ast::{AstNode, FdSpec, Program};

pub struct CodegenOptions {
    pub tape_size: usize,
    pub stack_size: usize,
    pub call_depth: usize,
    pub framebuffer: Option<(u32, u32)>,
    pub eof_value: u8,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        Self {
            tape_size: 65536,
            stack_size: 4096,
            call_depth: 256,
            framebuffer: None,
            eof_value: 0,
        }
    }
}

/// Result of code generation: C source and metadata flags
pub struct CodegenResult {
    pub c_source: String,
    pub uses_ffi: bool,
}

pub fn generate(program: &Program, opts: &CodegenOptions) -> CodegenResult {
    let uses_ffi = program_uses_ffi(&program.nodes);
    let c_source = generate_c(program, opts, uses_ffi);
    CodegenResult { c_source, uses_ffi }
}

fn program_uses_ffi(nodes: &[AstNode]) -> bool {
    for node in nodes {
        match node {
            AstNode::FfiCall(_, _) => return true,
            AstNode::Loop(body) | AstNode::SubDef(_, body) => {
                if program_uses_ffi(body) { return true; }
            }
            AstNode::ResultBlock(r, k) => {
                if program_uses_ffi(r) || program_uses_ffi(k) { return true; }
            }
            AstNode::Deref(inner) => {
                if program_uses_ffi(&[*inner.clone()]) { return true; }
            }
            _ => {}
        }
    }
    false
}

fn generate_c(program: &Program, opts: &CodegenOptions, uses_ffi: bool) -> String {
    let mut out = String::new();
    let mut ctx = GenCtx {
        indent: 1,
        subroutines: Vec::new(),
        eof_value: opts.eof_value,
        in_subroutine: false,
        in_result_block: false,
    };

    // First pass: collect subroutine definitions
    collect_subroutines(&program.nodes, &mut ctx.subroutines);

    // Emit header
    out.push_str(&emit_header(opts, uses_ffi));

    // Emit subroutine forward declarations
    for name in &ctx.subroutines {
        out.push_str(&format!("void bfpp_sub_{}(void);\n", mangle_name(name)));
    }
    if !ctx.subroutines.is_empty() {
        out.push('\n');
    }

    // Emit subroutine definitions
    for node in &program.nodes {
        if let AstNode::SubDef(name, body) = node {
            out.push_str(&format!("void bfpp_sub_{}(void) {{\n", mangle_name(name)));
            ctx.indent = 1;
            ctx.in_subroutine = true;
            // Call depth guard
            indent(&mut out, ctx.indent);
            out.push_str("if (++bfpp_call_depth > CALL_DEPTH) { fprintf(stderr, \"bfpp: call stack overflow\\n\"); exit(1); }\n");
            emit_nodes(&mut out, body, &mut ctx);
            indent(&mut out, ctx.indent);
            out.push_str("bfpp_call_depth--;\n");
            out.push_str("}\n\n");
        }
    }
    ctx.in_subroutine = false;

    // Emit main
    out.push_str("int main(void) {\n");
    ctx.indent = 1;

    if opts.framebuffer.is_some() {
        indent(&mut out, ctx.indent);
        out.push_str("#ifdef BFPP_FRAMEBUFFER\n");
        indent(&mut out, ctx.indent);
        out.push_str("bfpp_fb_init();\n");
        indent(&mut out, ctx.indent);
        out.push_str("#endif\n");
    }

    emit_nodes_skip_subdefs(&mut out, &program.nodes, &mut ctx);

    if opts.framebuffer.is_some() {
        indent(&mut out, ctx.indent);
        out.push_str("#ifdef BFPP_FRAMEBUFFER\n");
        indent(&mut out, ctx.indent);
        out.push_str("bfpp_fb_cleanup();\n");
        indent(&mut out, ctx.indent);
        out.push_str("#endif\n");
    }

    indent(&mut out, ctx.indent);
    out.push_str("return 0;\n");
    out.push_str("}\n");

    out
}

struct GenCtx {
    indent: usize,
    subroutines: Vec<String>,
    eof_value: u8,
    in_subroutine: bool,
    in_result_block: bool,
}

fn collect_subroutines(nodes: &[AstNode], names: &mut Vec<String>) {
    for node in nodes {
        if let AstNode::SubDef(name, _) = node {
            names.push(name.clone());
        }
    }
}

fn emit_header(opts: &CodegenOptions, uses_ffi: bool) -> String {
    let mut h = String::new();
    h.push_str("/* Generated by BF++ transpiler */\n");
    h.push_str("#include <stdio.h>\n");
    h.push_str("#include <stdlib.h>\n");
    h.push_str("#include <string.h>\n");
    h.push_str("#include <stdint.h>\n");
    h.push_str("#include <errno.h>\n");
    h.push_str("#include <unistd.h>\n");
    h.push_str("#include <sys/types.h>\n");
    h.push_str("#include <sys/stat.h>\n");
    h.push_str("#include <fcntl.h>\n");
    h.push_str("#include <sys/socket.h>\n");
    h.push_str("#include <netinet/in.h>\n");
    h.push_str("#include <arpa/inet.h>\n");
    h.push_str("#include <sys/syscall.h>\n");
    if uses_ffi {
        h.push_str("#include <dlfcn.h>\n");
    }
    h.push('\n');

    if let Some((w, h_)) = opts.framebuffer {
        h.push_str("#include <SDL2/SDL.h>\n");
        h.push_str("#define BFPP_FRAMEBUFFER\n");
        h.push_str(&format!("#define BFPP_FB_WIDTH {}\n", w));
        h.push_str(&format!("#define BFPP_FB_HEIGHT {}\n", h_));
        h.push_str("#define BFPP_FB_OFFSET (TAPE_SIZE - (BFPP_FB_WIDTH * BFPP_FB_HEIGHT * 3))\n");
    }

    h.push_str(&format!("#define TAPE_SIZE {}\n", opts.tape_size));
    h.push_str("#define TAPE_MASK (TAPE_SIZE - 1)\n");
    h.push_str(&format!("#define STACK_SIZE {}\n", opts.stack_size));
    h.push_str(&format!("#define CALL_DEPTH {}\n", opts.call_depth));
    h.push('\n');

    // Error code defines — single source of truth from error_codes.rs constants
    h.push_str(&format!("#define BFPP_OK {}\n", crate::error_codes::OK));
    h.push_str(&format!("#define BFPP_ERR_GENERIC {}\n", crate::error_codes::ERR_GENERIC));
    h.push_str(&format!("#define BFPP_ERR_NOT_FOUND {}\n", crate::error_codes::ERR_NOT_FOUND));
    h.push_str(&format!("#define BFPP_ERR_PERMISSION {}\n", crate::error_codes::ERR_PERMISSION));
    h.push_str(&format!("#define BFPP_ERR_OOM {}\n", crate::error_codes::ERR_OOM));
    h.push_str(&format!("#define BFPP_ERR_CONN_REFUSED {}\n", crate::error_codes::ERR_CONN_REFUSED));
    h.push_str(&format!("#define BFPP_ERR_INVALID_ARG {}\n", crate::error_codes::ERR_INVALID_ARG));
    h.push_str(&format!("#define BFPP_ERR_TIMEOUT {}\n", crate::error_codes::ERR_TIMEOUT));
    h.push_str(&format!("#define BFPP_ERR_EXISTS {}\n", crate::error_codes::ERR_EXISTS));
    h.push_str(&format!("#define BFPP_ERR_BUSY {}\n", crate::error_codes::ERR_BUSY));
    h.push_str(&format!("#define BFPP_ERR_PIPE {}\n", crate::error_codes::ERR_PIPE));
    h.push_str(&format!("#define BFPP_ERR_CONN_RESET {}\n", crate::error_codes::ERR_CONN_RESET));
    h.push_str(&format!("#define BFPP_ERR_ADDR_IN_USE {}\n", crate::error_codes::ERR_ADDR_IN_USE));
    h.push_str(&format!("#define BFPP_ERR_NOT_CONNECTED {}\n", crate::error_codes::ERR_NOT_CONNECTED));
    h.push_str(&format!("#define BFPP_ERR_INTERRUPTED {}\n", crate::error_codes::ERR_INTERRUPTED));
    h.push_str(&format!("#define BFPP_ERR_IO {}\n", crate::error_codes::ERR_IO));
    h.push_str(&format!("#define BFPP_ERR_NOLIB {}\n", crate::error_codes::ERR_NOLIB));
    h.push_str(&format!("#define BFPP_ERR_NOSYM {}\n", crate::error_codes::ERR_NOSYM));
    h.push('\n');

    // Core state
    h.push_str("static uint8_t tape[TAPE_SIZE];\n");
    h.push_str("static int ptr = 0;\n");
    h.push_str("static int bfpp_err = 0;\n");
    h.push_str("static uint64_t stack[STACK_SIZE];\n");
    h.push_str("static int sp = 0;\n");
    h.push_str("static int bfpp_call_depth = 0;\n");
    h.push_str("static uint8_t cell_width[TAPE_SIZE]; /* 0=continuation, 1,2,4,8 */\n");
    h.push('\n');

    // Helper: get cell value respecting width
    h.push_str(r#"static uint64_t bfpp_get(int p) {
    p &= TAPE_MASK;
    if (cell_width[p] == 0) { bfpp_err = BFPP_ERR_INVALID_ARG; return 0; } /* continuation byte */
    switch (cell_width[p]) {
        case 2: { uint16_t v; memcpy(&v, &tape[p], 2); return v; }
        case 4: { uint32_t v; memcpy(&v, &tape[p], 4); return v; }
        case 8: { uint64_t v; memcpy(&v, &tape[p], 8); return v; }
        default: return tape[p];
    }
}

static void bfpp_set(int p, uint64_t v) {
    p &= TAPE_MASK;
    if (cell_width[p] == 0) { bfpp_err = BFPP_ERR_INVALID_ARG; return; } /* continuation byte */
    switch (cell_width[p]) {
        case 2: { uint16_t t = (uint16_t)v; memcpy(&tape[p], &t, 2); break; }
        case 4: { uint32_t t = (uint32_t)v; memcpy(&tape[p], &t, 4); break; }
        case 8: { memcpy(&tape[p], &v, 8); break; }
        default: tape[p] = (uint8_t)v; break;
    }
}

static void bfpp_push(uint64_t val) {
    if (sp >= STACK_SIZE) { bfpp_err = BFPP_ERR_OOM; return; }
    stack[sp++] = val;
}

static uint64_t bfpp_pop(void) {
    if (sp <= 0) { bfpp_err = BFPP_ERR_INVALID_ARG; return 0; }
    return stack[--sp];
}

static void bfpp_cycle_width(int p) {
    int old_w = cell_width[p];
    int new_w, i;
    /* Release old sub-cells */
    for (i = 1; i < old_w; i++) cell_width[p + i] = 1;
    /* Determine new width */
    switch (old_w) {
        case 1: new_w = 2; break;
        case 2: new_w = 4; break;
        case 4: new_w = 8; break;
        default: new_w = 1; break;
    }
    /* Check sub-cells are available */
    for (i = 1; i < new_w; i++) {
        if (cell_width[p + i] != 1) {
            bfpp_err = BFPP_ERR_INVALID_ARG;
            cell_width[p] = 1; /* revert to 1-byte */
            return;
        }
    }
    cell_width[p] = new_w;
    /* Mark sub-cells as continuation (0) */
    for (i = 1; i < new_w; i++) cell_width[p + i] = 0;
}

"#);

    // errno mapping
    h.push_str(crate::error_codes::errno_mapping_c_source());
    h.push('\n');

    // Syscall wrapper
    h.push_str(r#"static void bfpp_syscall_exec(void) {
    uint64_t num = bfpp_get(ptr);
    uint64_t a1 = bfpp_get(ptr + 8);
    uint64_t a2 = bfpp_get(ptr + 16);
    uint64_t a3 = bfpp_get(ptr + 24);
    uint64_t a4 = bfpp_get(ptr + 32);
    uint64_t a5 = bfpp_get(ptr + 40);
    uint64_t a6 = bfpp_get(ptr + 48);
    long result = syscall(num, a1, a2, a3, a4, a5, a6);
    if (result < 0) {
        bfpp_err = bfpp_errno_to_code(errno);
        bfpp_set(ptr, (uint64_t)(-1));
    } else {
        bfpp_err = BFPP_OK;
        bfpp_set(ptr, (uint64_t)result);
    }
}

static void __attribute__((constructor)) bfpp_init(void) {
    memset(tape, 0, TAPE_SIZE);
    memset(cell_width, 1, TAPE_SIZE);
    memset(stack, 0, sizeof(stack));
}

"#);

    // SDL2 framebuffer support
    if opts.framebuffer.is_some() {
        h.push_str(r#"
#ifdef BFPP_FRAMEBUFFER
static SDL_Window *bfpp_fb_window = NULL;
static SDL_Renderer *bfpp_fb_renderer = NULL;
static SDL_Texture *bfpp_fb_texture = NULL;

static void bfpp_fb_init(void) {
    if (SDL_Init(SDL_INIT_VIDEO) < 0) {
        fprintf(stderr, "SDL init failed: %s\n", SDL_GetError());
        return;
    }
    bfpp_fb_window = SDL_CreateWindow("BF++",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        BFPP_FB_WIDTH, BFPP_FB_HEIGHT, SDL_WINDOW_SHOWN);
    if (!bfpp_fb_window) {
        fprintf(stderr, "SDL window failed: %s\n", SDL_GetError());
        SDL_Quit();
        return;
    }
    bfpp_fb_renderer = SDL_CreateRenderer(bfpp_fb_window, -1,
        SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
    if (!bfpp_fb_renderer) {
        bfpp_fb_renderer = SDL_CreateRenderer(bfpp_fb_window, -1, 0);
    }
    if (!bfpp_fb_renderer) {
        SDL_DestroyWindow(bfpp_fb_window);
        bfpp_fb_window = NULL;
        SDL_Quit();
        return;
    }
    bfpp_fb_texture = SDL_CreateTexture(bfpp_fb_renderer,
        SDL_PIXELFORMAT_RGB24, SDL_TEXTUREACCESS_STREAMING,
        BFPP_FB_WIDTH, BFPP_FB_HEIGHT);
}

static void bfpp_fb_flush(void) {
    if (!bfpp_fb_texture || !bfpp_fb_renderer) return;
    SDL_UpdateTexture(bfpp_fb_texture, NULL, &tape[BFPP_FB_OFFSET], BFPP_FB_WIDTH * 3);
    SDL_RenderClear(bfpp_fb_renderer);
    SDL_RenderCopy(bfpp_fb_renderer, bfpp_fb_texture, NULL, NULL);
    SDL_RenderPresent(bfpp_fb_renderer);
    SDL_Event e;
    while (SDL_PollEvent(&e)) {
        if (e.type == SDL_QUIT) {
            SDL_DestroyTexture(bfpp_fb_texture);
            SDL_DestroyRenderer(bfpp_fb_renderer);
            SDL_DestroyWindow(bfpp_fb_window);
            SDL_Quit();
            exit(0);
        }
    }
}

static void bfpp_fb_cleanup(void) {
    if (bfpp_fb_texture) SDL_DestroyTexture(bfpp_fb_texture);
    if (bfpp_fb_renderer) SDL_DestroyRenderer(bfpp_fb_renderer);
    if (bfpp_fb_window) SDL_DestroyWindow(bfpp_fb_window);
    SDL_Quit();
}
#endif

"#);
    }

    h
}

fn emit_nodes(out: &mut String, nodes: &[AstNode], ctx: &mut GenCtx) {
    for node in nodes {
        emit_node(out, node, ctx);
    }
}

fn emit_nodes_skip_subdefs(out: &mut String, nodes: &[AstNode], ctx: &mut GenCtx) {
    for node in nodes {
        if matches!(node, AstNode::SubDef(_, _)) {
            continue;
        }
        emit_node(out, node, ctx);
    }
}

fn emit_node(out: &mut String, node: &AstNode, ctx: &mut GenCtx) {
    match node {
        AstNode::MoveRight(n) => {
            indent(out, ctx.indent);
            out.push_str(&format!("ptr = (ptr + {}) & TAPE_MASK;\n", n));
        }
        AstNode::MoveLeft(n) => {
            indent(out, ctx.indent);
            out.push_str(&format!("ptr = (ptr - {} + TAPE_SIZE) & TAPE_MASK;\n", n));
        }
        AstNode::Increment(n) => {
            indent(out, ctx.indent);
            if *n == 1 {
                out.push_str("bfpp_set(ptr, bfpp_get(ptr) + 1);\n");
            } else {
                out.push_str(&format!("bfpp_set(ptr, bfpp_get(ptr) + {});\n", n));
            }
        }
        AstNode::Decrement(n) => {
            indent(out, ctx.indent);
            if *n == 1 {
                out.push_str("bfpp_set(ptr, bfpp_get(ptr) - 1);\n");
            } else {
                out.push_str(&format!("bfpp_set(ptr, bfpp_get(ptr) - {});\n", n));
            }
        }
        AstNode::Output => {
            indent(out, ctx.indent);
            out.push_str("putchar((int)bfpp_get(ptr));\n");
        }
        AstNode::Input => {
            indent(out, ctx.indent);
            out.push_str(&format!(
                "{{ int c = getchar(); bfpp_set(ptr, c == EOF ? {} : (uint64_t)c); }}\n",
                ctx.eof_value
            ));
        }
        AstNode::Loop(body) => {
            indent(out, ctx.indent);
            out.push_str("while (bfpp_get(ptr)) {\n");
            ctx.indent += 1;
            emit_nodes(out, body, ctx);
            ctx.indent -= 1;
            indent(out, ctx.indent);
            out.push_str("}\n");
        }

        // Extended memory
        AstNode::AbsoluteAddr => {
            indent(out, ctx.indent);
            out.push_str("ptr = (int)bfpp_get(ptr) & TAPE_MASK;\n");
        }
        AstNode::Deref(inner) => {
            indent(out, ctx.indent);
            out.push_str("{ int saved_ptr = ptr; ptr = (int)bfpp_get(ptr) & TAPE_MASK;\n");
            ctx.indent += 1;
            emit_node(out, inner, ctx);
            ctx.indent -= 1;
            indent(out, ctx.indent);
            out.push_str("ptr = saved_ptr; }\n");
        }
        AstNode::CellWidthCycle => {
            indent(out, ctx.indent);
            out.push_str("bfpp_cycle_width(ptr);\n");
        }
        AstNode::StringLit(bytes) => {
            indent(out, ctx.indent);
            out.push_str("{\n");
            ctx.indent += 1;
            indent(out, ctx.indent);
            out.push_str("static const uint8_t str_data[] = {");
            for (i, b) in bytes.iter().enumerate() {
                if i > 0 { out.push_str(", "); }
                out.push_str(&format!("{}", b));
            }
            out.push_str("};\n");
            indent(out, ctx.indent);
            out.push_str(&format!("memcpy(&tape[ptr], str_data, {});\n", bytes.len()));
            indent(out, ctx.indent);
            out.push_str(&format!("ptr = (ptr + {}) & TAPE_MASK;\n", bytes.len()));
            ctx.indent -= 1;
            indent(out, ctx.indent);
            out.push_str("}\n");
        }

        // Stack
        AstNode::Push => {
            indent(out, ctx.indent);
            out.push_str("bfpp_push(bfpp_get(ptr));\n");
        }
        AstNode::Pop => {
            indent(out, ctx.indent);
            out.push_str("bfpp_set(ptr, bfpp_pop());\n");
        }

        // Subroutines
        AstNode::SubDef(_, _) => {
            // Handled at top level — skip in-line
        }
        AstNode::SubCall(name) => {
            indent(out, ctx.indent);
            out.push_str(&format!("bfpp_sub_{}();\n", mangle_name(name)));
        }
        AstNode::Return => {
            indent(out, ctx.indent);
            if ctx.in_subroutine {
                out.push_str("bfpp_call_depth--; return;\n");
            } else {
                out.push_str("return 0;\n");
            }
        }

        // Syscall
        AstNode::Syscall => {
            indent(out, ctx.indent);
            out.push_str("bfpp_syscall_exec();\n");
        }
        AstNode::OutputFd(fd) => {
            indent(out, ctx.indent);
            match fd {
                FdSpec::Literal(n) => {
                    out.push_str(&format!(
                        "{{ uint8_t b = (uint8_t)bfpp_get(ptr); write({}, &b, 1); }}\n", n
                    ));
                }
                FdSpec::Indirect => {
                    out.push_str(
                        "{ uint8_t b = (uint8_t)bfpp_get(ptr); write((int)bfpp_get(ptr+1), &b, 1); }\n"
                    );
                }
            }
        }
        AstNode::InputFd(fd) => {
            indent(out, ctx.indent);
            match fd {
                FdSpec::Literal(n) => {
                    out.push_str(&format!(
                        "{{ uint8_t b; if (read({}, &b, 1) == 1) bfpp_set(ptr, b); else bfpp_set(ptr, {}); }}\n",
                        n, ctx.eof_value
                    ));
                }
                FdSpec::Indirect => {
                    out.push_str(&format!(
                        "{{ uint8_t b; if (read((int)bfpp_get(ptr+1), &b, 1) == 1) bfpp_set(ptr, b); else bfpp_set(ptr, {}); }}\n",
                        ctx.eof_value
                    ));
                }
            }
        }

        // Bitwise
        AstNode::BitOr => {
            indent(out, ctx.indent);
            out.push_str("bfpp_set(ptr, bfpp_get(ptr) | bfpp_get(ptr+1));\n");
        }
        AstNode::BitAnd => {
            indent(out, ctx.indent);
            out.push_str("bfpp_set(ptr, bfpp_get(ptr) & bfpp_get(ptr+1));\n");
        }
        AstNode::BitXor => {
            indent(out, ctx.indent);
            out.push_str("bfpp_set(ptr, bfpp_get(ptr) ^ bfpp_get(ptr+1));\n");
        }
        AstNode::ShiftLeft => {
            indent(out, ctx.indent);
            out.push_str("bfpp_set(ptr, bfpp_get(ptr) << bfpp_get(ptr+1));\n");
        }
        AstNode::ShiftRight => {
            indent(out, ctx.indent);
            out.push_str("bfpp_set(ptr, bfpp_get(ptr) >> bfpp_get(ptr+1));\n");
        }
        AstNode::BitNot => {
            indent(out, ctx.indent);
            out.push_str("bfpp_set(ptr, ~bfpp_get(ptr));\n");
        }

        // Error handling
        AstNode::ErrorRead => {
            indent(out, ctx.indent);
            out.push_str("bfpp_set(ptr, (uint64_t)bfpp_err);\n");
        }
        AstNode::ErrorWrite => {
            indent(out, ctx.indent);
            out.push_str("bfpp_err = (int)bfpp_get(ptr);\n");
        }
        AstNode::Propagate => {
            indent(out, ctx.indent);
            if ctx.in_result_block {
                out.push_str("if (bfpp_err) break;\n");
            } else if ctx.in_subroutine {
                out.push_str("if (bfpp_err) { bfpp_call_depth--; return; }\n");
            } else {
                out.push_str("if (bfpp_err) return;\n");
            }
        }
        AstNode::ResultBlock(result_body, catch_body) => {
            indent(out, ctx.indent);
            out.push_str("{\n");
            ctx.indent += 1;
            indent(out, ctx.indent);
            out.push_str("int saved_err = bfpp_err;\n");
            indent(out, ctx.indent);
            out.push_str("bfpp_err = BFPP_OK;\n");
            // Wrap R block in do/while(0) so ? (Propagate) can break to K block
            indent(out, ctx.indent);
            out.push_str("do {\n");
            ctx.indent += 1;
            let prev_in_result = ctx.in_result_block;
            ctx.in_result_block = true;
            emit_nodes(out, result_body, ctx);
            ctx.in_result_block = prev_in_result;
            ctx.indent -= 1;
            indent(out, ctx.indent);
            out.push_str("} while(0);\n");
            indent(out, ctx.indent);
            out.push_str("if (bfpp_err) {\n");
            ctx.indent += 1;
            emit_nodes(out, catch_body, ctx);
            ctx.indent -= 1;
            indent(out, ctx.indent);
            out.push_str("}\n");
            indent(out, ctx.indent);
            out.push_str("if (!bfpp_err) bfpp_err = saved_err;\n");
            ctx.indent -= 1;
            indent(out, ctx.indent);
            out.push_str("}\n");
        }

        // Tape address
        AstNode::TapeAddr => {
            indent(out, ctx.indent);
            out.push_str("bfpp_push((uint64_t)(uintptr_t)&tape[ptr]);\n");
        }

        // Framebuffer flush
        AstNode::FramebufferFlush => {
            indent(out, ctx.indent);
            out.push_str("#ifdef BFPP_FRAMEBUFFER\n");
            indent(out, ctx.indent);
            out.push_str("bfpp_fb_flush();\n");
            indent(out, ctx.indent);
            out.push_str("#endif\n");
        }

        // FFI call
        AstNode::FfiCall(lib, func) => {
            indent(out, ctx.indent);
            out.push_str("{\n");
            ctx.indent += 1;
            indent(out, ctx.indent);
            out.push_str(&format!("void *ffi_handle = dlopen(\"{}\", RTLD_LAZY);\n", lib));
            indent(out, ctx.indent);
            out.push_str("if (!ffi_handle) { bfpp_err = BFPP_ERR_NOLIB; }\n");
            indent(out, ctx.indent);
            out.push_str("else {\n");
            ctx.indent += 1;
            indent(out, ctx.indent);
            out.push_str(&format!(
                "long (*ffi_fn)(long,long,long,long,long,long) = (long(*)(long,long,long,long,long,long))dlsym(ffi_handle, \"{}\");\n",
                func
            ));
            indent(out, ctx.indent);
            out.push_str("if (!ffi_fn) { bfpp_err = BFPP_ERR_NOSYM; dlclose(ffi_handle); }\n");
            indent(out, ctx.indent);
            out.push_str("else {\n");
            ctx.indent += 1;
            indent(out, ctx.indent);
            out.push_str("long a1 = (long)bfpp_get(ptr + 8);\n");
            indent(out, ctx.indent);
            out.push_str("long a2 = (long)bfpp_get(ptr + 16);\n");
            indent(out, ctx.indent);
            out.push_str("long a3 = (long)bfpp_get(ptr + 24);\n");
            indent(out, ctx.indent);
            out.push_str("long a4 = (long)bfpp_get(ptr + 32);\n");
            indent(out, ctx.indent);
            out.push_str("long a5 = (long)bfpp_get(ptr + 40);\n");
            indent(out, ctx.indent);
            out.push_str("long a6 = (long)bfpp_get(ptr + 48);\n");
            indent(out, ctx.indent);
            out.push_str("long ffi_result = ffi_fn(a1, a2, a3, a4, a5, a6);\n");
            indent(out, ctx.indent);
            out.push_str("bfpp_set(ptr, (uint64_t)ffi_result);\n");
            indent(out, ctx.indent);
            out.push_str("bfpp_err = BFPP_OK;\n");
            indent(out, ctx.indent);
            out.push_str("dlclose(ffi_handle);\n");
            ctx.indent -= 1;
            indent(out, ctx.indent);
            out.push_str("}\n");
            ctx.indent -= 1;
            indent(out, ctx.indent);
            out.push_str("}\n");
            ctx.indent -= 1;
            indent(out, ctx.indent);
            out.push_str("}\n");
        }

        // Optimizer synthetic
        AstNode::Clear => {
            indent(out, ctx.indent);
            out.push_str("bfpp_set(ptr, 0);\n");
        }
        AstNode::ScanRight => {
            indent(out, ctx.indent);
            out.push_str("while (bfpp_get(ptr)) ptr = (ptr + 1) & TAPE_MASK;\n");
        }
        AstNode::ScanLeft => {
            indent(out, ctx.indent);
            out.push_str("while (bfpp_get(ptr)) ptr = (ptr - 1 + TAPE_SIZE) & TAPE_MASK;\n");
        }
        AstNode::MultiplyMove(pairs) => {
            indent(out, ctx.indent);
            out.push_str("{\n");
            ctx.indent += 1;
            indent(out, ctx.indent);
            out.push_str("uint64_t val = bfpp_get(ptr);\n");
            for (offset, factor) in pairs {
                indent(out, ctx.indent);
                if *offset >= 0 {
                    out.push_str(&format!(
                        "bfpp_set(ptr + {}, bfpp_get(ptr + {}) + val * {});\n",
                        offset, offset, factor
                    ));
                } else {
                    out.push_str(&format!(
                        "bfpp_set(ptr - {}, bfpp_get(ptr - {}) + val * {});\n",
                        -offset, -offset, factor
                    ));
                }
            }
            indent(out, ctx.indent);
            out.push_str("bfpp_set(ptr, 0);\n");
            ctx.indent -= 1;
            indent(out, ctx.indent);
            out.push_str("}\n");
        }
    }
}

fn indent(out: &mut String, level: usize) {
    for _ in 0..level {
        out.push_str("    ");
    }
}

/// Mangle a subroutine name for C identifier compatibility.
fn mangle_name(name: &str) -> String {
    let mut mangled = String::new();
    for c in name.chars() {
        match c {
            '>' => mangled.push_str("gt"),
            '<' => mangled.push_str("lt"),
            '+' => mangled.push_str("plus"),
            '-' => mangled.push_str("minus"),
            '.' => mangled.push_str("dot"),
            ',' => mangled.push_str("comma"),
            '[' => mangled.push_str("lbr"),
            ']' => mangled.push_str("rbr"),
            '@' => mangled.push_str("at"),
            '*' => mangled.push_str("star"),
            '%' => mangled.push_str("pct"),
            '$' => mangled.push_str("dollar"),
            '~' => mangled.push_str("tilde"),
            '\\' => mangled.push_str("bslash"),
            '|' => mangled.push_str("pipe"),
            '&' => mangled.push_str("amp"),
            '^' => mangled.push_str("caret"),
            '_' => mangled.push('_'),
            c if c.is_alphanumeric() => mangled.push(c),
            _ => mangled.push_str(&format!("u{:02x}", c as u32)),
        }
    }
    mangled
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::lex;
    use crate::parser::parse;

    #[test]
    fn test_hello_world_generates() {
        let tokens = lex("++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.").unwrap();
        let program = parse(&tokens).unwrap();
        let result = generate(&program, &CodegenOptions::default());
        assert!(result.c_source.contains("int main(void)"));
        assert!(result.c_source.contains("while (bfpp_get(ptr))"));
        assert!(result.c_source.contains("putchar"));
    }

    #[test]
    fn test_subroutine_codegen() {
        let tokens = lex("!#pr{.^} !#pr").unwrap();
        let program = parse(&tokens).unwrap();
        let result = generate(&program, &CodegenOptions::default());
        assert!(result.c_source.contains("void bfpp_sub_pr(void)"));
        assert!(result.c_source.contains("bfpp_sub_pr();"));
    }

    #[test]
    fn test_error_handling_codegen() {
        let tokens = lex("R{+}K{-}").unwrap();
        let program = parse(&tokens).unwrap();
        let result = generate(&program, &CodegenOptions::default());
        assert!(result.c_source.contains("saved_err"));
        assert!(result.c_source.contains("if (bfpp_err)"));
    }

    #[test]
    fn test_name_mangling() {
        assert_eq!(mangle_name(".>"), "dotgt");
        assert_eq!(mangle_name("pr"), "pr");
        assert_eq!(mangle_name("m*"), "mstar");
        assert_eq!(mangle_name("tcp"), "tcp");
    }

    #[test]
    fn test_tape_addr_codegen() {
        let tokens = lex("T").unwrap();
        let program = parse(&tokens).unwrap();
        let result = generate(&program, &CodegenOptions::default());
        assert!(result.c_source.contains("bfpp_push((uint64_t)(uintptr_t)&tape[ptr])"));
    }

    #[test]
    fn test_framebuffer_flush_codegen() {
        let tokens = lex("F").unwrap();
        let program = parse(&tokens).unwrap();
        let result = generate(&program, &CodegenOptions::default());
        assert!(result.c_source.contains("bfpp_fb_flush"));
    }

    #[test]
    fn test_ffi_codegen() {
        let tokens = lex(r#"\ffi "libm.so.6" "ceil""#).unwrap();
        let program = parse(&tokens).unwrap();
        let result = generate(&program, &CodegenOptions::default());
        assert!(result.c_source.contains("dlopen"));
        assert!(result.c_source.contains("dlsym"));
        assert!(result.c_source.contains("libm.so.6"));
        assert!(result.c_source.contains("ceil"));
        assert!(result.uses_ffi);
    }
}
